import AppKit
import CryptoKit
import EventEngine
import Foundation
import Shared

// MARK: - Items

/// Something you copied: text, a link, an image or files.
public struct ClipboardItem: Identifiable, Codable, Equatable, Sendable {
    public enum Kind: String, Codable, Sendable, CaseIterable {
        case text, link, image, file

        public var title: String {
            switch self {
            case .text: "Text"
            case .link: "Link"
            case .image: "Image"
            case .file: "File"
            }
        }
    }

    public var id: UUID
    public var kind: Kind
    /// The text or link. For files, their paths, one per line. Empty for images.
    public var text: String
    public var imageWidth: Int?
    public var imageHeight: Int?
    public var sourceBundleId: String?
    public var sourceName: String?
    public var copiedAt: Date
    public var isPinned: Bool
    /// Same content, same fingerprint — copying something again moves it to the top.
    public var fingerprint: String

    public init(
        id: UUID = UUID(), kind: Kind, text: String, imageWidth: Int? = nil, imageHeight: Int? = nil,
        sourceBundleId: String? = nil, sourceName: String? = nil, copiedAt: Date = Date(),
        isPinned: Bool = false, fingerprint: String
    ) {
        self.id = id
        self.kind = kind
        self.text = text
        self.imageWidth = imageWidth
        self.imageHeight = imageHeight
        self.sourceBundleId = sourceBundleId
        self.sourceName = sourceName
        self.copiedAt = copiedAt
        self.isPinned = isPinned
        self.fingerprint = fingerprint
    }

    public var filePaths: [String] {
        kind == .file ? text.split(separator: "\n").map(String.init) : []
    }

    /// One line for lists: the first line of text, the image size, or the file name(s).
    public var title: String {
        switch kind {
        case .text, .link:
            let line = text.split(whereSeparator: \.isNewline)
                .lazy.map { $0.trimmingCharacters(in: .whitespaces) }
                .first { !$0.isEmpty } ?? ""
            return String(line.prefix(200))
        case .image:
            if let imageWidth, let imageHeight { return "Image (\(imageWidth) × \(imageHeight))" }
            return "Image"
        case .file:
            let names = filePaths.map { ($0 as NSString).lastPathComponent }
            guard let first = names.first else { return "File" }
            return names.count == 1 ? first : "\(first) and \(names.count - 1) more"
        }
    }
}

/// What the clipboard held, before it becomes an item.
public struct ClipboardCapture: Sendable, Equatable {
    public var kind: ClipboardItem.Kind
    public var text: String
    /// PNG data, for images.
    public var imageData: Data?
    public var imageWidth: Int?
    public var imageHeight: Int?
    public var fingerprint: String
}

/// How long unpinned items are kept.
public enum ClipboardRetention: String, CaseIterable, Identifiable, Sendable {
    case day, week, month, threeMonths, year

    public var id: Self { self }

    public var title: String {
        switch self {
        case .day: "1 Day"
        case .week: "1 Week"
        case .month: "1 Month"
        case .threeMonths: "3 Months"
        case .year: "1 Year"
        }
    }

    public var interval: TimeInterval {
        let day: TimeInterval = 24 * 60 * 60
        return switch self {
        case .day: day
        case .week: 7 * day
        case .month: 30 * day
        case .threeMonths: 91 * day
        case .year: 365 * day
        }
    }
}

// MARK: - Reading the clipboard

public enum ClipboardReader {
    /// Marks HyperKeys' own short-lived clipboard writes (paste-and-restore), so they stay out of history.
    public static let ownWriteType = NSPasteboard.PasteboardType("com.hyperkeys.transient")

    /// Types that say "don't remember this": passwords and other secrets (nspasteboard.org), and our own writes.
    static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        ownWriteType.rawValue,
    ]

    static let maxTextLength = 1_000_000
    static let maxImageBytes = 30 * 1024 * 1024

    public static func capture(from pasteboard: NSPasteboard) -> ClipboardCapture? {
        let types = pasteboard.types ?? []
        guard !types.contains(where: { privateTypes.contains($0.rawValue) }) else { return nil }

        let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL] ?? []
        if !fileURLs.isEmpty {
            let paths = fileURLs.map(\.path).joined(separator: "\n")
            return ClipboardCapture(kind: .file, text: paths, fingerprint: fingerprint(.file, Data(paths.utf8)))
        }

        let string = pasteboard.string(forType: .string)
        let hasImage = types.contains(.png) || types.contains(.tiff)
        // An image copied from a browser often comes with its address; the image is what was copied.
        if hasImage, string.map(isLink) ?? true, let image = image(from: pasteboard) {
            return image
        }

        guard let string, !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              string.utf16.count <= maxTextLength
        else { return nil }
        let kind: ClipboardItem.Kind = isLink(string) ? .link : .text
        return ClipboardCapture(kind: kind, text: string, fingerprint: fingerprint(kind, Data(string.utf8)))
    }

    private static func image(from pasteboard: NSPasteboard) -> ClipboardCapture? {
        let data: Data
        if let png = pasteboard.data(forType: .png) {
            data = png
        } else if let tiff = pasteboard.data(forType: .tiff),
                  let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
            data = png
        } else {
            return nil
        }
        guard data.count <= maxImageBytes, let rep = NSBitmapImageRep(data: data) else { return nil }
        return ClipboardCapture(
            kind: .image, text: "", imageData: data,
            imageWidth: rep.pixelsWide, imageHeight: rep.pixelsHigh,
            fingerprint: fingerprint(.image, data)
        )
    }

    /// A single web or mail address with nothing around it.
    public static func isLink(_ string: String) -> Bool {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              let url = URL(string: trimmed), let scheme = url.scheme?.lowercased()
        else { return false }
        switch scheme {
        case "http", "https", "ftp": return url.host?.isEmpty == false
        case "mailto": return trimmed.count > "mailto:".count
        default: return false
        }
    }

    static func fingerprint(_ kind: ClipboardItem.Kind, _ data: Data) -> String {
        var hasher = SHA256()
        hasher.update(data: Data(kind.rawValue.utf8))
        hasher.update(data: data)
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
}

// MARK: - Writing items back

public enum ClipboardWriter {
    /// Puts an item on the clipboard, marked as HyperKeys' own so the monitor doesn't record it again.
    @MainActor
    public static func write(_ item: ClipboardItem, imageURL: URL?, to pasteboard: NSPasteboard = .general) {
        var items: [NSPasteboardItem] = []
        switch item.kind {
        case .text:
            let entry = NSPasteboardItem()
            entry.setString(item.text, forType: .string)
            items.append(entry)
        case .link:
            let entry = NSPasteboardItem()
            entry.setString(item.text, forType: .string)
            entry.setString(item.text.trimmingCharacters(in: .whitespacesAndNewlines), forType: .URL)
            items.append(entry)
        case .image:
            guard let imageURL, let png = try? Data(contentsOf: imageURL) else { return }
            let entry = NSPasteboardItem()
            entry.setData(png, forType: .png)
            if let tiff = NSBitmapImageRep(data: png)?.tiffRepresentation {
                entry.setData(tiff, forType: .tiff)
            }
            items.append(entry)
        case .file:
            for path in item.filePaths {
                let entry = NSPasteboardItem()
                entry.setString(URL(fileURLWithPath: path).absoluteString, forType: .fileURL)
                items.append(entry)
            }
        }
        guard !items.isEmpty else { return }
        for entry in items {
            entry.setString("", forType: ClipboardReader.ownWriteType)
        }
        pasteboard.clearContents()
        pasteboard.writeObjects(items)
    }
}

// MARK: - Store

/// Your clipboard history, kept on this Mac only (not in config.json, not synced).
@MainActor
@Observable
public final class ClipboardHistoryStore {
    public static let shared = ClipboardHistoryStore()

    /// Newest first.
    public private(set) var items: [ClipboardItem] = []

    public var isEnabled: Bool {
        didSet { defaults.set(isEnabled, forKey: Keys.enabled) }
    }

    public var retention: ClipboardRetention {
        didSet {
            defaults.set(retention.rawValue, forKey: Keys.retention)
            prune()
        }
    }

    /// A regular shortcut that opens the panel, like ⇧⌘V, besides any Hyper shortcut.
    public var hotKey: KeyCombo? {
        didSet { defaults.set(hotKey?.string, forKey: Keys.hotKey) }
    }

    /// Apps whose copies are never saved. Password managers to start with.
    public var ignoredBundleIds: [String] {
        didSet { defaults.set(ignoredBundleIds, forKey: Keys.ignored) }
    }

    public static let defaultIgnoredBundleIds = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.keychainaccess",
        "com.apple.Passwords",
    ]

    /// Unpinned items beyond this are dropped, oldest first.
    public static let maxItems = 1000

    public let folder: URL
    private let defaults: UserDefaults

    private enum Keys {
        static let enabled = "clipboardHistoryEnabled"
        static let retention = "clipboardHistoryRetention"
        static let ignored = "clipboardHistoryIgnoredApps"
        static let hotKey = "clipboardHistoryHotKey"
    }

    public init(
        folder: URL = Persistence.appSupportURL.appendingPathComponent("ClipboardHistory", isDirectory: true),
        defaults: UserDefaults = .standard
    ) {
        self.folder = folder
        self.defaults = defaults
        isEnabled = defaults.object(forKey: Keys.enabled) as? Bool ?? true
        retention = defaults.string(forKey: Keys.retention).flatMap(ClipboardRetention.init) ?? .month
        ignoredBundleIds = defaults.stringArray(forKey: Keys.ignored) ?? Self.defaultIgnoredBundleIds
        hotKey = defaults.string(forKey: Keys.hotKey).flatMap(KeyCombo.init(string:))
        load()
        prune()
    }

    public var pinnedItems: [ClipboardItem] { items.filter(\.isPinned) }

    public func item(id: UUID) -> ClipboardItem? {
        items.first { $0.id == id }
    }

    /// Where an image item's PNG lives.
    public func imageURL(for item: ClipboardItem) -> URL? {
        item.kind == .image ? imagesFolder.appendingPathComponent("\(item.id.uuidString).png") : nil
    }

    // MARK: Changes

    public func record(_ capture: ClipboardCapture, sourceBundleId: String?, sourceName: String?, now: Date = Date()) {
        if let index = items.firstIndex(where: { $0.fingerprint == capture.fingerprint }) {
            var item = items.remove(at: index)
            item.copiedAt = now
            item.sourceBundleId = sourceBundleId ?? item.sourceBundleId
            item.sourceName = sourceName ?? item.sourceName
            items.insert(item, at: 0)
        } else {
            let item = ClipboardItem(
                kind: capture.kind, text: capture.text,
                imageWidth: capture.imageWidth, imageHeight: capture.imageHeight,
                sourceBundleId: sourceBundleId, sourceName: sourceName,
                copiedAt: now, fingerprint: capture.fingerprint
            )
            if let data = capture.imageData, let url = imageURL(for: item) {
                try? FileManager.default.createDirectory(at: imagesFolder, withIntermediateDirectories: true)
                try? data.write(to: url, options: .atomic)
            }
            items.insert(item, at: 0)
        }
        prune(now: now)
        save()
    }

    /// Moves an item to the top after it's pasted or copied again.
    public func markUsed(id: UUID, now: Date = Date()) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        var item = items.remove(at: index)
        item.copiedAt = now
        items.insert(item, at: 0)
        save()
    }

    public func togglePin(id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        items[index].isPinned.toggle()
        save()
    }

    public func delete(id: UUID) {
        guard let index = items.firstIndex(where: { $0.id == id }) else { return }
        removeFiles(of: items.remove(at: index))
        save()
    }

    /// Deletes everything except pinned items.
    public func clear() {
        let removed = items.filter { !$0.isPinned }
        items.removeAll { !$0.isPinned }
        removed.forEach(removeFiles)
        save()
    }

    /// Drops unpinned items older than the retention period, then the oldest beyond `maxItems`.
    public func prune(now: Date = Date()) {
        let cutoff = now.addingTimeInterval(-retention.interval)
        var unpinnedKept = 0
        var removed: [ClipboardItem] = []
        items.removeAll { item in
            guard !item.isPinned else { return false }
            if item.copiedAt < cutoff || unpinnedKept >= Self.maxItems {
                removed.append(item)
                return true
            }
            unpinnedKept += 1
            return false
        }
        guard !removed.isEmpty else { return }
        removed.forEach(removeFiles)
        save()
    }

    // MARK: Storage

    private var historyURL: URL { folder.appendingPathComponent("history.json") }
    private var imagesFolder: URL { folder.appendingPathComponent("images", isDirectory: true) }

    private func load() {
        guard let data = try? Data(contentsOf: historyURL),
              let saved = try? JSONDecoder.history.decode([ClipboardItem].self, from: data)
        else { return }
        items = saved.sorted { $0.copiedAt > $1.copiedAt }
    }

    private func save() {
        do {
            try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
            try JSONEncoder.history.encode(items).write(to: historyURL, options: .atomic)
        } catch {
            NSLog("[HyperKeys] Couldn't save clipboard history: \(error.localizedDescription)")
        }
    }

    private func removeFiles(of item: ClipboardItem) {
        if let url = imageURL(for: item) {
            try? FileManager.default.removeItem(at: url)
        }
    }
}

private extension JSONEncoder {
    static var history: JSONEncoder {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        return encoder
    }
}

private extension JSONDecoder {
    static var history: JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }
}

// MARK: - Monitor

/// Watches the clipboard and records what you copy. macOS has no "clipboard changed"
/// notification, so this checks the change count twice a second — a cheap integer read.
@MainActor
public final class ClipboardMonitor {
    public static let shared = ClipboardMonitor()

    private let store: ClipboardHistoryStore
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChangeCount: Int
    private var ignoreUntil = Date.distantPast

    public init(store: ClipboardHistoryStore = .shared, pasteboard: NSPasteboard = .general) {
        self.store = store
        self.pasteboard = pasteboard
        lastChangeCount = pasteboard.changeCount
    }

    public func start() {
        guard timer == nil else { return }
        lastChangeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        timer.tolerance = 0.2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    public func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Skips clipboard changes for a moment (HyperKeys copying a selection to read it).
    public func ignoreChanges(for seconds: TimeInterval) {
        ignoreUntil = Date().addingTimeInterval(seconds)
    }

    /// Records the clipboard if it changed since the last check, crediting the app in front.
    public func check() {
        let app = NSWorkspace.shared.frontmostApplication
        check(sourceBundleId: app?.bundleIdentifier, sourceName: app?.localizedName)
    }

    func check(sourceBundleId: String?, sourceName: String?) {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard store.isEnabled, Date() > ignoreUntil else { return }
        if let sourceBundleId, store.ignoredBundleIds.contains(sourceBundleId) { return }
        guard let capture = ClipboardReader.capture(from: pasteboard) else { return }
        store.record(capture, sourceBundleId: sourceBundleId, sourceName: sourceName)
    }
}
